### ISSUE TITLE
Investigate real-time oriented robot communication

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_cloud#1]
For real-time communication with kitt, first oriented towards web based drive commands.

- [x] Create wiki page on this repo listing several options for communicating with the robot.
- [x] Pros and cons of each library

Resources to investigate:
robot-web-tools
rabbitmq, celery
zmq
restful endpoints

**Comment by illiu** [comment]
For now, my vote is for robot web tools. It would be the easiest to integrate and to test. If it does not work out, we can try ZMQ. RabbitMQ looks like overkill for our purposes.

**Comment by griswaldbrooks** [comment]
Can you write up a follow on ticket about using robot-web-tools to do something so we can see it work?
